# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AudioCard(Model):
    """A audio card.

    :param aspect: Aspect ratio of thumbnail/media placeholder, allowed values
     are "16:9" and "9:16".
    :type aspect: str
    :param title: Title of the card.
    :type title: str
    :param subtitle: Subtitle of the card.
    :type subtitle: str
    :param text: Text of the card.
    :type text: str
    :param image: Thumbnail placeholder.
    :type image: ~azure.botframework.connector.models.ThumbnailUrl
    :param media: Array of media Url objects.
    :type media: list[~azure.botframework.connector.models.MediaUrl]
    :param buttons: Set of actions applicable to the current card.
    :type buttons: list[~azure.botframework.connector.models.CardAction]
    :param shareable: Is it OK for this content to be shareable with others
     (default: true).
    :type shareable: bool
    :param autoloop: Should the client loop playback at end of content
     (default: true).
    :type autoloop: bool
    :param autostart: Should the client automatically start playback of video
     in this card (default: true).
    :type autostart: bool
    :param value: Supplementary parameter for this card.
    :type value: object
    """

    _attribute_map = {
        'aspect': {'key': 'aspect', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'subtitle': {'key': 'subtitle', 'type': 'str'},
        'text': {'key': 'text', 'type': 'str'},
        'image': {'key': 'image', 'type': 'ThumbnailUrl'},
        'media': {'key': 'media', 'type': '[MediaUrl]'},
        'buttons': {'key': 'buttons', 'type': '[CardAction]'},
        'shareable': {'key': 'shareable', 'type': 'bool'},
        'autoloop': {'key': 'autoloop', 'type': 'bool'},
        'autostart': {'key': 'autostart', 'type': 'bool'},
        'value': {'key': 'value', 'type': 'object'},
    }

    def __init__(self, aspect=None, title=None, subtitle=None, text=None, image=None, media=None, buttons=None, shareable=None, autoloop=None, autostart=None, value=None):
        super(AudioCard, self).__init__()
        self.aspect = aspect
        self.title = title
        self.subtitle = subtitle
        self.text = text
        self.image = image
        self.media = media
        self.buttons = buttons
        self.shareable = shareable
        self.autoloop = autoloop
        self.autostart = autostart
        self.value = value
