# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class ErrorCode(Enum):

    four_zero_zero = "400"
    four_zero_one = "401"
    four_zero_three = "403"
    four_zero_four = "404"
    four_zero_five = "405"
    four_two_nine = "429"
    five_zero_zero = "500"
    five_zero_three = "503"


class ActivityType(Enum):

    message = "message"
    conversation_update = "conversationUpdate"
    contact_relation_update = "contactRelationUpdate"
    typing = "typing"
    end_of_conversation = "endOfConversation"
    event = "event"
    invoke = "invoke"


class TextFormat(Enum):

    markdown = "markdown"
    plain = "plain"
    xml = "xml"


class InputHint(Enum):

    accepting_input = "acceptingInput"
    expecting_input = "expectingInput"
    ignoring_input = "ignoringInput"
