# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ConversationAccount(Model):
    """Channel account information for a conversation.

    :param is_group: Is this a reference to a group. Default value: False .
    :type is_group: bool
    :param id: The ID that identifies the conversation. The ID is unique per
     channel. If the channel starts the conversion, it sets this ID; otherwise,
     the bot sets this property to the ID that it gets back in the response
     when it starts the conversation (Example: joe@smith.com, or @joesmith or
     123456).
    :type id: str
    :param name: A display name that can be used to identify the conversation.
    :type name: str
    """

    _attribute_map = {
        'is_group': {'key': 'isGroup', 'type': 'bool'},
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, is_group=False, id=None, name=None):
        super(ConversationAccount, self).__init__()
        self.is_group = is_group
        self.id = id
        self.name = name
