# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ConversationParameters(Model):
    """Parameters for creating a new conversation.

    :param is_group: Indicates if this is a group conversation.
    :type is_group: bool
    :param bot: The bot address for this conversation.
    :type bot: ~azure.botframework.connector.models.ChannelAccount
    :param members: Members to add to the conversation.
    :type members: list[~azure.botframework.connector.models.ChannelAccount]
    :param topic_name: (Optional) Topic title of a conversation (if supported
     by the channel).
    :type topic_name: str
    :param activity: (Optional) Use this activity as the initial message to
     the conversation when creating a new conversation.
    :type activity: ~azure.botframework.connector.models.Activity
    :param channel_data: Channel specific payload for creating the
     conversation.
    :type channel_data: object
    """

    _validation = {
        'bot': {'required': True},
        'members': {'required': True},
    }

    _attribute_map = {
        'is_group': {'key': 'isGroup', 'type': 'bool'},
        'bot': {'key': 'bot', 'type': 'ChannelAccount'},
        'members': {'key': 'members', 'type': '[ChannelAccount]'},
        'topic_name': {'key': 'topicName', 'type': 'str'},
        'activity': {'key': 'activity', 'type': 'Activity'},
        'channel_data': {'key': 'channelData', 'type': 'object'},
    }

    def __init__(self, bot, members, is_group=None, topic_name=None, activity=None, channel_data=None):
        super(ConversationParameters, self).__init__()
        self.is_group = is_group
        self.bot = bot
        self.members = members
        self.topic_name = topic_name
        self.activity = activity
        self.channel_data = channel_data
