# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Fact(Model):
    """Set of key-value pairs. Advantage of this section is that key and value
    properties will be rendered with default style information with some
    delimiter between them. So there is no need for developer to specify style
    information.

    :param key: Name of the fact.
    :type key: str
    :param value: Value of the fact.
    :type value: str
    """

    _attribute_map = {
        'key': {'key': 'key', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self, key=None, value=None):
        super(Fact, self).__init__()
        self.key = key
        self.value = value
