# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Place(Model):
    """Place (entity type: "https://schema.org/Place").

    :param address: Address of the place (may be `string` or complex object of
     type "PostalAddress").
    :type address: object
    :param geo: A GeoCoordinates object that specifies the geographical
     coordinates of the place.
    :type geo: ~azure.botframework.connector.models.GeoCoordinates
    :param has_map: Map to the place (may be `string` (URL) or complex object
     of type "Map").
    :type has_map: object
    :param type: This object's type. Always set to Place.
    :type type: str
    :param name: Name of the place.
    :type name: str
    """

    _attribute_map = {
        'address': {'key': 'address', 'type': 'object'},
        'geo': {'key': 'geo', 'type': 'GeoCoordinates'},
        'has_map': {'key': 'hasMap', 'type': 'object'},
        'type': {'key': 'type', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, address=None, geo=None, has_map=None, type=None, name=None):
        super(Place, self).__init__()
        self.address = address
        self.geo = geo
        self.has_map = has_map
        self.type = type
        self.name = name
