# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReceiptCard(Model):
    """A receipt card.

    :param title: Title displayed at the top of the receipt.
    :type title: str
    :param items: Array of Receipt Items.
    :type items: list[~azure.botframework.connector.models.ReceiptItem]
    :param facts: Array of Fact objects (key-value pairs) that specify
     information about the purchase.
    :type facts: list[~azure.botframework.connector.models.Fact]
    :param tap: This action will be activated when user taps on the card.
    :type tap: ~azure.botframework.connector.models.CardAction
    :param total: A currency-formatted string that specifies the total
     purchase price, including all applicable taxes.
    :type total: str
    :param tax: A currency-formatted string that specifies the amount of tax
     applied to the purchase.
    :type tax: str
    :param vat: A currency-formatted string that specifies the amount of value
     added tax (VAT) applied to the purchase price.
    :type vat: str
    :param buttons: Set of actions applicable to the current card.
    :type buttons: list[~azure.botframework.connector.models.CardAction]
    """

    _attribute_map = {
        'title': {'key': 'title', 'type': 'str'},
        'items': {'key': 'items', 'type': '[ReceiptItem]'},
        'facts': {'key': 'facts', 'type': '[Fact]'},
        'tap': {'key': 'tap', 'type': 'CardAction'},
        'total': {'key': 'total', 'type': 'str'},
        'tax': {'key': 'tax', 'type': 'str'},
        'vat': {'key': 'vat', 'type': 'str'},
        'buttons': {'key': 'buttons', 'type': '[CardAction]'},
    }

    def __init__(self, title=None, items=None, facts=None, tap=None, total=None, tax=None, vat=None, buttons=None):
        super(ReceiptCard, self).__init__()
        self.title = title
        self.items = items
        self.facts = facts
        self.tap = tap
        self.total = total
        self.tax = tax
        self.vat = vat
        self.buttons = buttons
