# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReceiptItem(Model):
    """An item on a receipt card.

    :param title: Title of the line item.
    :type title: str
    :param subtitle: Subtitle to be displayed under the line item’s title.
    :type subtitle: str
    :param text: Description of the line item.
    :type text: str
    :param image: Thumbnail image to display next to the line item.
    :type image: ~azure.botframework.connector.models.CardImage
    :param price: A currency-formatted string that specifies the total price
     of all units purchased.
    :type price: str
    :param quantity: A numeric string that specifies the number of units
     purchased.
    :type quantity: str
    :param tap: This action will be activated when user taps on the Item
     bubble.
    :type tap: ~azure.botframework.connector.models.CardAction
    """

    _attribute_map = {
        'title': {'key': 'title', 'type': 'str'},
        'subtitle': {'key': 'subtitle', 'type': 'str'},
        'text': {'key': 'text', 'type': 'str'},
        'image': {'key': 'image', 'type': 'CardImage'},
        'price': {'key': 'price', 'type': 'str'},
        'quantity': {'key': 'quantity', 'type': 'str'},
        'tap': {'key': 'tap', 'type': 'CardAction'},
    }

    def __init__(self, title=None, subtitle=None, text=None, image=None, price=None, quantity=None, tap=None):
        super(ReceiptItem, self).__init__()
        self.title = title
        self.subtitle = subtitle
        self.text = text
        self.image = image
        self.price = price
        self.quantity = quantity
        self.tap = tap
