# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SignInCard(Model):
    """A card representing a request to sign in.

    :param text: Text for signIn request.
    :type text: str
    :param buttons: Action to use to perform signIn.
    :type buttons: list[~azure.botframework.connector.models.CardAction]
    """

    _attribute_map = {
        'text': {'key': 'text', 'type': 'str'},
        'buttons': {'key': 'buttons', 'type': '[CardAction]'},
    }

    def __init__(self, text=None, buttons=None):
        super(SignInCard, self).__init__()
        self.text = text
        self.buttons = buttons
