# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ThumbnailUrl(Model):
    """Object describing a media thumbnail.

    :param url: URL pointing to an thumbnail to use for media content.
    :type url: str
    :param alt: Alt text to display for screen readers on the thumbnail image.
    :type alt: str
    """

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
        'alt': {'key': 'alt', 'type': 'str'},
    }

    def __init__(self, url=None, alt=None):
        super(ThumbnailUrl, self).__init__()
        self.url = url
        self.alt = alt
